### ISSUE TITLE
[BUG] errors

### ISSUE THREAD

**Issue by mrdiega** [webpashtet/ConnectInfo#2]
css 144
mm 1280
ConnectInfo v1.0.4

sometime get errors after player connect
![connectinfo error](https://github.com/webpashtet/ConnectInfo/assets/79888956/036027bd-3207-47fb-a10e-3b7fab20bd48)
![connectinfo error2](https://github.com/webpashtet/ConnectInfo/assets/79888956/f485cfb0-a1a8-44ce-bd72-5d3b1faa6de4)
![connectinfo error3](https://github.com/webpashtet/ConnectInfo/assets/79888956/4a793dca-1a6c-4f65-bb22-7cdda3e91db6)

**Comment by webpashtet** [comment]
Это ошибки не моего плагина, а плагина Modularity

**Comment by webpashtet** [comment]
А та ошибка про null - это не нашелся ip в базе
